### ISSUE TITLE
Add option to ignore/swallow errors

### ISSUE THREAD

**Issue by dan-kirberger** [drone-plugins/drone-s3-cache#50]
It would be handy to mark this task to indicate we dont want s3 failures to tank our build:
```
  restore_from_cache:
    image: docker.target.com/drone/drone-s3-cache
    pull: true
    restore: true
    required: false // look at me!
```
note the `required: false`

For many, this plugin might be used as a convenience to improve build performance. Momentary hiccups in s3 connectivity should not break the build, but simply slow it down.
